apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: target-demo-cluster-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./target-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: target-demo-kubeconfig