apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: c6b62ae0-1186-4868-804b-a7e1793fe52b
    azure.workload.identity/tenant-id: e90b6a60-a35f-4a16-8095-5b6163395d56
  name: workload-identity-sa
  namespace: external-secrets
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubecredentials
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: e90b6a60-a35f-4a16-8095-5b6163395d56
      vaultUrl: https://external-kubeconfig.vault.azure.net/
      serviceAccountRef:
        name: workload-identity-sa
        namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: target-demo-kubeconfig
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubecredentials
  data:
    - secretKey: value.yaml
      remoteRef:
        key: secret/target-demo-kubeconfig