apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: management-cluster-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./management-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
