apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  interval: 3m
  timeout: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.7
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 3m
  releaseName: external-secrets-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: strimzi-cluster-operator
  namespace: flux-system
spec:
  targetNamespace: kafka
  interval: 3m
  timeout: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-helm
      interval: 3m
  releaseName: strimzi-cluster-operator